#!/bin/bash

exec matlab -nojvm -nosplash -nodesktop -r 'matlab.engine.shareEngine' &

./main.py

# Acá termina el programa -> killeo el matlab
kill $(ps aux | grep 'matlab.engine.shareEngine' | grep -v "grep" | awk '{print $2}')
